---
- name: jira-systemctl-daemon-reload
  systemd:
    daemon_reload: true
  changed_when: false
  ignore_errors: true
  when: jira_manual_upgrade == False

- name: jira-systemctl-restart
  service:
    name: "jira"
    state: "restarted"
    enabled: true
  loop: "{{ ansible_play_hosts }}"
  delegate_to: "{{ item }}"
  run_once: true
  changed_when: false
  ignore_errors: true
  when: jira_manual_upgrade == False
