---
- name: Monit install and configure fact
  set_fact:
   monit_install: "{{ (lvm_roles_node is defined and lvm_roles_node|length>0) or (monit_mounts and monit_mounts|length>0) or monit_smtp is defined or monit_system_monitoring is defined }}" 

- name: Monit
  package:
    name: "{{ monit_rpm_url|default('monit') }}"
    state: present
  when: monit_install

- name: Ensure monit is running
  service: "name=monit state=started enabled=yes"
  when: monit_install

- name: monitrc
  template:
    dest: /etc/monitrc
    mode: "600"
    src: monitrc.j2
  when: monit_install
  notify: reload monit

- name: Disk space
  template: 
    dest: /etc/monit.d/diskspace
    src: diskspace.j2
  when: monit_install
  notify: reload monit

- name: Smtp
  template:
    dest: /etc/monit.d/smtp
    src: smtp.j2
  when: monit_smtp is defined
  notify: reload monit

- name: System
  template:
    dest: /etc/monit.d/system
    src: system.j2
  when: monit_system_monitoring is defined
  notify: reload monit

- name: Get nodes monit roles
  set_fact: monit_roles_node="{{ monit_roles_supported | intersect(ansible_role_names_cleaned) }}"

- name: Logs
  template:
    dest: /etc/monit.d/log
    src: log.j2
  notify: reload monit
