---
sonarqube_home: /opt/sonarqube
sonarqube_download_validate_certs: true

sonarqube_version: 6.7

sonarqube_java_bin: 
  Debian: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
  RedHat: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64/jre/bin/java
  
# Web, Elastic search, Compute engine
sonarqube_xms: 128m
sonarqube_xmx: 512m
sonarqube_es_xms: 512m
sonarqube_es_xmx: 512m
sonarqube_ce_xms: 128m
sonarqube_ce_xmx: 512m

sonarqube_web_port: 9000
sonarqube_web_context: '/sonarqube'

sonarqube_database_username: sonarqube
sonarqube_database_password: supersecure

sonarqube_database_host: localhost
sonarqube_database_port: "5432"
sonarqube_database_name: sonarqube
sonarqube_database_admin_username: ansible
sonarqube_database_admin_password: supersecure
sonarqube_database_template: template0

sonarqube_python_library: python-psycopg2

# Elasticsearch settings
sonarqube_max_map_count: '262144'
sonarqube_pam_limits_hard_nofile: '262144' # 65535 minimum

#sonarqube_plugin_download_timeout: 180 # seconds, default 10
sonarqube_plugins: []

#sonarqube_proxy:
#  host: localhost
#  port: 3128

# Facts set by lcm role - only
# sonarqube_database_name_version: sonarqube_6_7
# sonarqube_home_version: /opt/sonarqube/sonarqube_6_7

sonarqube_jmx_remote:
  enable: no
  remote_port: 10443
  remote_port_ce: 10444  
  reader_password: supersecure 
  admin_password: supersecure
  # hostname: {{ ansible_default_ipv4.address }}
  hostname: "1.1.1.4"  

sonarqube_versions: 
  6.7:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.zip
    checksum: sha256:426ef44431814609ea279c3afd889b4b93c1cc630be7666cad34f0bc70b5d3b0
  7.9.1:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.1.zip
    checksum: sha256:67f3ccae79245397480b0947d7a0b5661dc650b87f368b39365044ebcc88ada0
  7.9.2:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.2.zip
    checksum: sha256:e4111983996ffee407288cf1ee16703c940ce9ba92728dad0c09c6b5a22b6148
  8.1.0:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.1.0.31237.zip
    checksum: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

sonarqube_versions_sequence: ["6.7", "7.9.1", "7.9.2", "8.1.0"]

#sonarqube_ldap_bindpassword
#sonarqube_ldap:
#  url: ldap://localhost:389/
#  bindDn: cn=admin
#  # authentication: 
#  user: 
#    baseDn: ou=people,dc=cicd,dc=tech
#    request: uid={login}
#    realNameAttribute: cn
#    emailAttribute: mail
#  group: 
#    baseDn: ou=groups,dc=cicd,dc=tech
#    request: (&(objectClass=groupOfNames)(member={dn}))
#    idAttribute: cn
