# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_box = 'generic/centos7'
# vagrant_box = 'c2/centos7' # for lvm role
# vagrant_box = 'generic/ubuntu1804'

# Ansible inventory
ansible_groups = {
  'proxy' => ['proxy'],
  'reverse-proxy' => ['proxy'],
  'nfs' => ['proxy'],
  'postgresql' => ['postgresql'],
  'sonarqube' => ['sonarqube'],
  'jenkins' => ['jenkins'],  
  'nexus' => ['nexus'],
  'opendj' => ['proxy'],
  'env' => ['env'],  
  'myapp_servers' => %w(myapp myapp2),
  # 'backup' => %w(sonarqube nexus), # TODO
  'all:vars' => { 'sudo_include_sudoersd' => 'yes' },
  'postgresql:vars' => { 'hostvar' => 'abc' },
  'sonarqube:vars' => { 'sonarqube_database_host' => '1.1.1.2' },
  'nfs:vars' => { 'nfs_exports' => ['/nfs/backup *(rw,sync,no_root_squash)'] }
}
# ansible_host_vars = { 'postgresql' => { 'xyz' => 80 } }

# Vagrant nodes
nodes = {}
nodes['sonarqube'] = { 'ip' => '1.1.1.4', 'plays' => %w(sonarqube), 'memory' => 1024 * 4 }
nodes['postgresql'] = {  'ip' => '1.1.1.2', 'plays' => %w(postgresql) }
nodes['proxy'] = {  'ip' => '1.1.1.3', 'plays' => %w(proxy reverse-proxy nfs opendj) }
nodes['nexus'] = {  'ip' => '1.1.1.7', 'plays' => %w(nexus), 'memory' => 1024 * 4, 'cpus' => 4 }
nodes['env'] = {  'ip' => '1.1.1.8', 'plays' => %w(env), 'memory' => 512 }
nodes['jenkins'] = {  'ip' => '1.1.1.9', 'plays' => %w(jenkins), 'memory' => 1024 * 4 }
nodes['sites'] = {  'ip' => '1.1.1.10', 'plays' => %w(sites) }
nodes['bitbucket'] = {  'ip' => '1.1.1.11', 'plays' => %w(bitbucket), 'memory' => 1024 * 4 }
# nodes['myapp'] = { 'ip' => '1.1.1.5', 'plays' => %w(myapp) }
# nodes['myapp2'] = { 'ip' => '1.1.1.6', 'plays' => %w(myapp) }

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant'
  nodes.each do |n, a|
    bx = a['box'] || vagrant_box
    shell_provision = 'sudo apt-get update && sudo apt-get -y install python'
    shell_provision = 'sudo yum update -y && sudo yum -y install python && echo PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin | sudo tee /etc/environment > /dev/null' if bx.include? 'centos'

    config.vm.define n do |cfg|
      cfg.vm.hostname = n # .e.g. sonarqube
      cfg.vm.box = bx
      cfg.vm.network 'private_network', ip: a['ip']
      cfg.vm.provider 'virtualbox' do |vb|
        vb.gui = false
        vb.memory = a['memory'] || 1024
        vb.cpus = a['cpus'] || 2
      end
      cfg.vm.provision 'shell', inline: shell_provision
      a['plays'].each do |p|
        cfg.vm.provision 'ansible' do |ansible|
          ansible.config_file = '../plays/ansible.cfg'
          ansible.playbook = "../plays/#{p}.yml"
          ansible.groups = ansible_groups
          # ansible.host_vars = ansible_host_vars
          # ansible.inventory_path = '../development.ini' # NO!
          # ansible.galaxy_role_file = '../roles/requirements.yml'
          # ansible.galaxy_roles_path = '~/.ansible/roles'
          # ansible.verbose = 'vvv'
        end
      end
    end
  end
end
