---
- name: postgresql.yml | All roles
  hosts: postgresql
  become: True

  roles:
    - { role: common,                     tags: ["common"] }
    - { role: galaxyproject.postgresql,   tags: ["postgresql"] }
    - { role: postgresql,                 tags: ["postgresql"] }
