---
- name: "Get installed packages"
  package_facts:
    manager: "auto"

- name: Download RPMs
  get_url:
    url: "{{ oracle_client_rpms[item]['url'] }}"
    dest: "/tmp/{{ oracle_client_rpms[item]['url']|basename }}"
    timeout: 300
    mode: 1373
    headers:
      oraclelicense: accept-securebackup-cookie
  register: get_url_result
  until: get_url_result is succeeded
  when: oracle_client_rpms[item]['name'] not in ansible_facts.packages
  with_items: "{{ oracle_client_installs }}"

- name: Install packages
  package:
    name: "/tmp/{{ oracle_client_rpms[item]['url']|basename }}"
  when: oracle_client_rpms[item]['name'] not in ansible_facts.packages
  with_items: "{{ oracle_client_installs }}"

- name: Oracle environment PATH, LD_LIBRARY_PATH, NLS_LANG
  copy:
    content: |
      export PATH=$PATH:{{ oracle_client_bin_path }}
      export LD_LIBRARY_PATH={{ oracle_client_lib_path }}:$LD_LIBRARY_PATH
      export NLS_LANG=american_america.al32utf8
    dest: /etc/profile.d/oracle.sh 
  when: oracle_client_bin_path is defined
